### ISSUE TITLE
cmd 파싱 함수 구현

### ISSUE THREAD

**Issue by lina0322** [lina0322/42seoul_minishell#11]

**Comment by som-syom** [comment]
cmd처리 전, 토크나이저 과정에서 환경변수 치환이 되어야합니다
예외케이스
```
$ export hello=123
$ echo "$hello""world"
```
환경변수 치환이 나중에 일어나는 경우 => 토크나이저 과정 중간에 따옴표들끼리 붙어져서 `$helloworld` 를 찾기 때문에 `$hello` 치환이 안됨!
따라서 큰따옴표 토크나이저 옮기는 과정에서 처리해야함!
(+작은따옴표는 문자그대로 출력, 아무것도없는 common의 경우에도 치환해줘야함)

**Comment by lina0322** [comment]
- [x] 띄어쓰기 관련 핸들링
```C
bash-3.2$ echo "hi" "hi"hi
hi hihi
bash-3.2$ echo hi hi hi
hi hi hi
```

**Comment by lina0322** [comment]
- [x] 환경변수
- [x] "", '' 안에 \
- [x] 백슬래시 처리된 문자 어떻게 cmd에서 넘겨주지..?

**Comment by lina0322** [comment]
🐛띄어쓰기 없이 ; | 앞뒤로 연달아 입력하면, cmd 분할 안됨

**Comment by lina0322** [comment]
🐛
- [x] 1. 띄어쓰기 없이 ; | 앞뒤로 연달아 입력하면, cmd 분할 안됨
- [x] 2. 스페이스가 맨 앞에 있으면 안됨..
- [x] 3. 바로 엔터치면 터짐
😡🤯😡🤯😡🤯😡🤯😡🤯😡🤯😡🤯
내 머리도 터진듯

**Comment by som-syom** [comment]
일단 충돌나는부분은 주석처리하였음
충돌나는 부분 -> parse_cmd 맨아래줄 memset 인데 여기서 memset을 하는 이유를 잘 모르겠음 ㅠㅠ

**Comment by lina0322** [comment]
지난 새벽에 어디서 충돌나는지 못찾고 껐는데, 찾아주셨군요 솜솜.. 최고👍
그 부분 관련해서 수정했습니당!

지금은 `충돌나는 부분 -> parse_cmd 맨아래줄 memset`이 위치에서 토큰 프리하고, 
main에서 cmd 프리후, 둘 다 memset 해줍니다.

이유는 
1. 토큰은 해당 위치에서 사용이 끝나므로 free해줘야 한다고 생각
2. cmd는 아직 위치를 몰라서 main에서 free해줌
3. memset하는 이유는, free하고 나면 없어서(?) 새 토큰과 cmd를 진행할 수 없음! <- 다음 진행 대기(?)

지금 생각에는 token과 cmd를 memset하는게 while문 도입부가 되어야할 것 같은데, 오늘 회의때 의견 나누면 좋을 것 같습니다!

**Comment by lina0322** [comment]
🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛
<img width="865" alt="스크린샷 2021-04-04 22 01 21" src="https://user-images.githubusercontent.com/49546979/113509558-4d067f00-9591-11eb-85cd-3785592a7f89.png">

**Comment by lina0322** [comment]
🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛

회의때 makefile에 주석처리한거 풀면 세그폴트랑 멤릭 볼 수 있다해서, 주석 풀고 터미널에서 돌렸는데욥...
이렇게 나오는데 어떻게 해야할지 모르겠어서.... 여기 우선 남겨둡니당..😭

바로 엔터쳤을때 터지는 상황입니다~~~~

<img width="926" alt="스크린샷 2021-04-04 22 19 34" src="https://user-images.githubusercontent.com/49546979/113510082-d74fe280-9593-11eb-9262-48c69faa51dc.png">

-> 우선 memset 사용 안하고 하는 중!!

지금 생각에는 free를 했는데, memset을 할 필요가 있나 궁금해졌습니당!
처음에 init_state할때 memset하면 head들만 0을 가지나요? 아니면 token_head등의 내부에도 0을 가지게 되나요?
head들만 가지는거라면 memset을 안해도 될거같은데.. 잘모르게씀다

**Comment by lina0322** [comment]
🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛

cmd가 2개가 되면 터지는 상황... token_free and cmd_free 터지므...ㅠㅠ

<img width="973" alt="스크린샷 2021-04-04 22 50 31" src="https://user-images.githubusercontent.com/49546979/113510937-357ec480-9598-11eb-809e-f9f9aca9f273.png">

**Comment by lina0322** [comment]
첫번째 cmd만 출력되는게 어떤 문제인지 모르겠다...

**Comment by som-syom** [comment]
무엇이 문제인지 모르겠어요..... 아직 터지는 케이스가 나오지않아서...

**Comment by som-syom** [comment]
cmd 2개일때 오류는 해결했습니다
cmd의 char **av malloc할때 더블포인터가 아니라 포인터로 말록해서 생긴 문제같아요 그래서 free할때 더블free로 나옵니다

근데 테스트하는 과정에서
asdf;asdf 이 테스트는 이제 멀쩡하게 돌아가는데
asdf ;asdf 이렇게 테스트를 넣으면 다시 더블free로 터집니다
아직 cmd만드는 과정을 자세히 아는게 아니지만 
스페이스자체를 토큰에 넣어놔서 ac가 스페이스까지 인식하면서 첫 cmd의 ac가 2가 됩니다.... 
그리고 make_cmd로 들어가면서 그 ac 로 바로 malloc을 해버립니다.
사실 저는 토크나이저 과정자체에서 type space가 없는게 제일 좋다고 생각하는데 
코드 수정하기가 어렵다면 ac 셀때 스페이스는 안세도록 수정해야 할것 같아요.... 
ac세는 과정도 그렇지만 나중에 cmd 의 av 를 다룰때 스페이스도 같이 들어가서 
빌트인이나 기능구현에서도 꼬일수도 있을거같고... 
스페이스가 쭉한번에 나와버리는 경우에도 뭔가 꼬일거같습니다........ ㅠㅠ

**Comment by som-syom** [comment]
> 🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛
> 
> 회의때 makefile에 주석처리한거 풀면 세그폴트랑 멤릭 볼 수 있다해서, 주석 풀고 터미널에서 돌렸는데욥...
> 이렇게 나오는데 어떻게 해야할지 모르겠어서.... 여기 우선 남겨둡니당..😭
> 
> 바로 엔터쳤을때 터지는 상황입니다~~~~
> 
> <img alt="스크린샷 2021-04-04 22 19 34" width="926" src="https://user-images.githubusercontent.com/49546979/113510082-d74fe280-9593-11eb-9262-48c69faa51dc.png">
> 
> -> 우선 memset 사용 안하고 하는 중!!
> 
> 지금 생각에는 free를 했는데, memset을 할 필요가 있나 궁금해졌습니당!
> 처음에 init_state할때 memset하면 head들만 0을 가지나요? 아니면 token_head등의 내부에도 0을 가지게 되나요?
> head들만 가지는거라면 memset을 안해도 될거같은데.. 잘모르게씀다

그리고 처음 init_state를 할때는 state구조체에 대해 0으로 셋하는거라
state내의 t_cmd 형식의 *cmd 자체 값이 0이 되는거라 cmd 내의 변수(av 나 ac같은)에 대해선 0으로 초기화가 되지 않습니다
이부분은 짠 코드에 따라 다르긴한데 만약 init되어있는지 체크하는 함수가 있거나 초기화가 필요하다면  따로 memset을 해야하고,
아니라면 굳이 안해도 됩니다!

**Comment by som-syom** [comment]
오류 나는 케이스
![image](https://user-images.githubusercontent.com/60869490/113626691-70b6eb80-969d-11eb-8a85-fb08faaa434a.png)
이렇게 입력했는데 
![image](https://user-images.githubusercontent.com/60869490/113626748-81fff800-969d-11eb-9bb6-901465a60eef.png)
cmd에 av가 첫번째 인자로만 저장이 되어있고 ac도 저장이 이상하게 되어있습니다
cmd 관련 함수는 제가 손을 못댈거같아서 ㅠㅠ 수정부탁드립니다...

**Comment by som-syom** [comment]
글쓰고나마자 오류 찾았습니다 ㅠㅠ
![image](https://user-images.githubusercontent.com/60869490/113627324-4dd90700-969e-11eb-96fc-542f410229c5.png)
여기서 tmp로 옮겨놓고 free하는건 cmd->av 여서 두번 free해서 생겼던거 같고
cmd 를 tmp로 수정하니까 에러는 안뜹니다

근데 다른 에러가 생겼는데
cmd 2개인 명령어를 처음입력할땐 문제가 없다가 두번째 입력하면 cmd구조체 malloc할때 세그폴트가 뜹니다
![image](https://user-images.githubusercontent.com/60869490/113629599-9ba33e80-96a1-11eb-82fb-0d8c595f0a3f.png)
(수정) 😇이부분은 memset 부분을 주석처리하니 해결되었습니다...
(memset은 안하는게 맞는거같아요...)
근데 cmd 함수 구조들을 보고있는데 구조가 조금 이상하게 짜여진것 같아요ㅠㅠㅠ 
head가 처음부터 안들어가있고 구조체malloc 전에 구조체 내에서 쓸 av를 malloc하고, 그다음에 구조체 malloc 을 하는데,
뭔가 구조가 잘 이해가 안가기도 하고, 에러가 나기 전 (처음 명령어 입력시) 저장된 cmd도 이상이 있습니다...
![image](https://user-images.githubusercontent.com/60869490/113629891-ffc60280-96a1-11eb-949c-6d5e2ab8e3a7.png)
입력한 명령어
![image](https://user-images.githubusercontent.com/60869490/113629875-f89ef480-96a1-11eb-80f1-225dfa4464f8.png)
저장된 cmd
확인 부탁드립니당....

**Comment by lina0322** [comment]
good godd
memset과 free관련한 부분 완전 좋아용!!

추가로 달아주신 코멘트 관련해서

### [1]
> 스페이스자체를 토큰에 넣어놔서 ac가 스페이스까지 인식하면서 첫 cmd의 ac가 2가 됩니다....

처음 구조상에는 스페이스 제외하고 갯수 체크했는데, 잠시 기타 다양한 이유로 확인차 체크하지 않는 중! 
일부로 해당부분 삭제했어용ㅎㅎㅎ
마지막에 조정할 예정입니다:)
그래서 ac 개수 이상하게 나오는거랍니당ㅎㅎㅎ

### [2]
> head가 처음부터 안들어가있고 
구조체malloc 전에 구조체 내에서 쓸 av를 malloc하고, 그다음에 구조체 malloc 을 하는데,

head가 처음부터 안들어가있다는 말이 무슨말인지 모르겠어요🥲
그리고 token만들때도 구조체가 생성되기전에 str을 먼저 malloc하는데... 구조체에 들어갈 내용이 있어야 구조체를 만드는거라
이것도 어떤거 말하는지 모르겠네용...

추가로!
위에서 터지는 것 많이 이야기 해주셨는데, 우선 체크해주셔서 감사합니당🙇🏻‍♀️
위에서 발생했던 memset과 free오류때문에
free를 주석처리 해두어발생한 문제도 있고, cmd를 아직 완성한 부분이 아니기 때문에:)
제가 열심히 완성해볼게요. 조금만 더 기다려주세효!

**Comment by lina0322** [comment]
🅽🅾🆁🅼
parse_cmd 함수 2줄 줄여야함

**Comment by som-syom** [comment]
![image](https://user-images.githubusercontent.com/60869490/114471486-b0487f00-9c2b-11eb-8511-ab5a51c01a68.png)
명령어없는경우 세그폴트 뜹니다... 
syntax error 처리하면 execute에서 확인하면 해결될거 같은데 어떻게 되어가고있나용

**Comment by som-syom** [comment]
-  Double Quotes
echo " \\\" \$HOME $HOME "
echo "'$HOME'"

![image](https://user-images.githubusercontent.com/60869490/114473761-c8220200-9c2f-11eb-94d8-2e3a9b185f1e.png)
bash의 경우
![image](https://user-images.githubusercontent.com/60869490/114473645-9b6dea80-9c2f-11eb-8a84-1016a8e1b48a.png)
minishell의 경우

테스트할 부분 체크하는데 아래 두 경우가 제대로 출력되지 않습니다 확인부탁드려용

**Comment by lina0322** [comment]
- [x] Double Quotes
> echo " \" $HOME $HOME "
echo "'$HOME'"

큰 따옴표 내부에, 백슬래시 뒤 "있는 경우 따로 체크하였습니다.
두번째 경우는 함수 분리하는 과정에서, 길이 체크 잘못되어 수정하였습니다.

- [x] syntax error 처리 
> issue #14 에 error 코드 정리되어있습니다!
