### ISSUE TITLE
free 해주기

### ISSUE THREAD

**Issue by lina0322** [lina0322/42seoul_minishell#12]
- [x] export print하고나서 배열 free
- [x] env free
- [x] cmd free
- [x] token free
- [x] path free

**Comment by som-syom** [comment]
path free 함수도 추가해주세용

**Comment by som-syom** [comment]
어차피 다 링크드리스트라 링크드리스트 인자로 받아서 free시켜주는 함수 하나 있으면 될거같아요

**Comment by lina0322** [comment]
🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛
<img width="865" alt="스크린샷 2021-04-04 22 01 21" src="https://user-images.githubusercontent.com/49546979/113509558-4d067f00-9591-11eb-85cd-3785592a7f89.png">

해당 내용 cmd로 이동
