### ISSUE TITLE
history

### ISSUE THREAD

**Issue by lina0322** [lina0322/42seoul_minishell#16]

**Comment by som-syom** [comment]
수정해야할 부분 !
- 위로 쭉 올라갔다가 내려가는건 자연스럽게 잘 나오는데, 중간쯤에서 위아래키 반복적으로 누르면 안바뀌고 같은 값만 나옴
이부분은 아마 head만 갖고 놀았어야 했는데 up키에선 head, down키에선 head->prev를 출력해서 그런거 같음...
head만 갖고 놀려면 up키에선 그대로, down키에선 처음부터 head = head->prev 해줘야할것 같음
- 함수 길이 때문에 나눌수 있는 부분 나눠야함

**Comment by lina0322** [comment]
다소미 최고... 반해버렸누
