### ISSUE TITLE
프롬프트 함수 구현

### ISSUE THREAD

**Issue by lina0322** [lina0322/42seoul_minishell#6]

**Comment by som-syom** [comment]
❗️서브젝트 변경으로 완전 수정이 필요함

**Comment by som-syom** [comment]
현재 prompt 파일 안에 prompt 함수와 prompt2 함수가 있는데,
이전버전으로 테스트를 할 경우 prompt 만 사용해서 입력받으면 됩니다!
서브젝트 변경 버전은 prompt2에서 작업 중!!!

**Comment by som-syom** [comment]
처리 해야할 것
- [x] 백스페이스 할때 input에 저장된 값 하나씩 지우는 기능 추가
- [x] is_backslash 함수 수정
- [x] 엔터 입력 받았을때 다음줄 넘어가게하고 반복문 탈출하도록 변경
- [x] bash > 출력하는 부분 수정
- [x] bash > 안지워지도록 수정

**Comment by som-syom** [comment]
exit 으로 나갈때
인자있는경우 exit(인자)
없는경우는 exit(s->ret)? 이건가 확실히 알아보기
